import { Container } from "react-bootstrap";
import styled from "styled-components";
// @ts-ignore
import Reveal from "react-reveal/Reveal";

const PageInfo = styled.div`
  font-size: 16px;
  padding: 0 35px;
  border-radius: 5px;
  margin: 25px 0;
  background-color: #121212;
  height: 600px;
  overflow-y: scroll;
  @media (max-width: 767px) {
    padding: 0 20px;
    margin: 15px 0;
  }
  & P {
    margin-bottom: 10px;
  }
  ::-webkit-scrollbar {
    display: none;
  }
`;
const PageInfoWrapper = styled.div`
  background-color: #121212;
  border: 0.5px solid #ff4cb5;
  border-radius: 5px;
`;
const RecordTitle = styled.h4`
  font-size: 24px;
  text-transform: uppercase;
  font-weight: 900;
  line-height: 36px;
  @media (max-width: 767px) {
    font-size: 20px;
  }
`;
const RecordPra = styled.p`
  font-size: 16px;
  margin-bottom: 30px;
  @media (max-width: 767px) {
    font-size: 16px;
  }
`;
const SubTitle = styled.div`
  font-weight: bold;
  margin-bottom: 5px;
`;
const Description = styled.p`
  /* text-align: justify; */
`;

const Terms = () => {
  return (
    <Reveal effect="fadeInRight">
      <Container style={{ paddingTop: "35px" }}>
        <PageInfoWrapper>
          <PageInfo>
            <RecordTitle>TERMS & CONDITIONS</RecordTitle>
            <RecordPra>
              <Description>
                The Doge Pound is a collection of digital artworks (NFTs) running on the Ethereum network. This website
                is only an interface allowing participants to buy digital collectibles in presale. Users are entirely
                responsible for the safety and management of their own private Ethereum wallets and validating all
                transactions andcontracts generated by this website before approval. Furthermore, as The Doge Pound
                smart contract runs on theEthereum network, there is no ability to undo, reverse, or restoreany
                transactions.
              </Description>
              <Description>
                This website and its connected services are provided “as is” and“as available” without a warranty of any
                kind. By using this website, you are accepting sole responsibility for any and all transactions
                involving The Doge Pound digital collectibles.
              </Description>
            </RecordPra>

            <RecordTitle className="mt-4">OWNERSHIP</RecordTitle>
            <RecordPra>
              <SubTitle>- You Own the NFT</SubTitle>
              <Description>
                Each The Doge Pound is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the
                underlying The Doge Pound Token, completely. Ownership of the NFT is mediated entirely by the Smart
                Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership
                of any The Doge Pound Token.
              </Description>
            </RecordPra>
            <RecordPra>
              <SubTitle>- Personal Use</SubTitle>
              <Description>
                Subject to your continued compliance with these Terms, we grant you a worldwide, royalty-free license to
                use, copy, and display the purchased Art, along with any extensions that you choose to create or use,
                solely for the following purposes:
              </Description>
              <Description>· for your own personal, non-commercial use;</Description>
              <Description>
                · as part of a marketplace that permits the purchase and sale of your Doge Token /NFT, provided that the
                marketplace cryptographically verifies each Doge Pound Token owner’s rights to display the Art for their
                Doge Pound Token to ensure that only the actual owner can display the Art.
              </Description>
              <Description>
                · as part of a third-party website or application that permits theinclusion, involvement, or
                participation of your Doge Pound Token, provided that the website/application cryptographically
                verifieseach Doge Pound Token owner’s rights to display the Art for their Doge Pound Token to ensure
                that only the actual owner can display the Art, and provided that the Art is no longer visible once the
                owner of The Doge Pound Token leaves the website/application.
              </Description>
            </RecordPra>
            <RecordPra style={{ marginBottom: "0" }}>
              <SubTitle>- Commercial Use</SubTitle>
              <Description>
                Subject to your continued compliance with these Terms, we grantyou an unlimited, worldwide license to
                use, copy, and display the purchased Art for the purpose of creating derivative works basedupon the Art
                (“Commercial Use”). Examples of such CommercialUse would e.g., be the use of the Art to produce and sell
                merchandise products (T-Shirts, etc.) displaying copies of the Art. For the sake of clarity, nothing in
                this Section will be deemed to restrict you from
              </Description>
              <Description>
                · owning or operating a marketplace that permits the use and sale of The Doge Pound Token generally,
                provided that the marketplace cryptographically verifies each Doge Pound Token owner’s rights to display
                the Art for their Doge Pound Token to ensure that only the actual owner can display the Art.
              </Description>
              <Description>
                · owning or operating a third-party website or application that permits the inclusion, involvement, or
                participation of Doge Pound Tokens generally, provided that the third-party website or application
                cryptographically verifies each The Doge Pound Token owner’srights to display the Art for their Doge
                Pound Token to ensure that onlythe actual owner can display the Art, and provided that the Art is no
                longer visible once the owner of the purchased Doge Pound Token leaves the website/application;
              </Description>
              <Description style={{ marginBottom: "0" }}>· or earning revenue from any of the foregoing.</Description>
            </RecordPra>
          </PageInfo>
        </PageInfoWrapper>
      </Container>
    </Reveal>
  );
};
export default Terms;
